using Statistics;
NumberCruncher test = new NumberCruncher();
test.addNumber(5);
test.addNumber(6);
test.addNumber(7);
test.addNumber(8);
test.displayData();
test.removeLastNumber();
test.displayData();
//test.total();